### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by syptic** [rsavoj/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - Make sure to use a relevant name for the link instead of the url itself. Also links for user/host id are not needed.
- [ ] All relevant code examples written with backticks (```)
  - Code examples given without backticks or as screenshots
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - Missing keystroke count and timer. 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good job overall make sure to have relevant hypertexts, use code blocks and measure optimization for the last example

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page
```

**Comment by rsavoj** [comment]
I just wanted to clarify where we are supposed to add the keystrokes and timer. Is it for the SSH key or the optimizing remote running examples.

**Comment by syptic** [comment]
The optimizing remote running section.
